version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./ssl:/opt/atat/atst/ssl
      - ./config:/opt/atst/atst/config
      - sockets:/var/run/uwsgi
    environment:
      PGHOST: host.docker.internal
      REDIS_URI: "redis://host.docker.internal:6379"

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./deploy/docker/sample.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - sockets:/var/run/uwsgi
    depends_on:
      - backend
    ports:
      - 8080:80

volumes:
  sockets:
