namespace: atat
resources:
  - azure.yml
  - uwsgi-config.yml
  - atst-envvars-configmap.yml
  - atst-nginx-configmap.yml
  - atst-worker-envvars-configmap.yml
  - crls-sync.yaml
  - pgsslrootcert.yml
  - volume-claim.yml
  - nginx-client-ca-bundle.yml
  - acme-challenges.yml
  - aadpodidentity.yml
  - nginx-snippets.yml
